name: ui_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  math_expressions: ^2.6.0
  riverpod_generator: ^2.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/failure.mp3

flutter_gen:
  integrations:
    flutter_svg: true
    flutter_png: true
    flutter_mp3: true
  